<div style="
    padding: 15px 20px;
    margin: 10px 0;
    border-left: 8px solid #4F7942;
    background-color: rgba(255, 191, 0, 0.05);
    border-radius: 4px;
">

## Table of Contents:

- [Imports and Seed](#imports-and-seed)
- [Machine Learning Model Selection and Definition](#machine-learning-model-selection-and-definition)
- [Neural Network Model Selection and Definition](#neural-network-model-selection-and-definition)
- [Normal Data Modeling](#normal-data-modeling)
- [Complex Data Modeling](#complex-data-modeling)
- [Normal vs. Complex Data](#normal-vs.-complex-data)

</div>

### ORIENTATION:

This file is intended to select and define-as closely as possible-a Machine Learning (ML) and Neural Network (NN) model in order to train and evaluate the performace with the normal tabular data vs. the complex network feature engineered data.

---

### IMPORTANT NOTE:

yay

---

### SUMMARY:
- ML Selection
    - We will use *Random Forest Classifier* to maintain as much explainability and generally solve the data imbalance in the complex data
- NN Selection
    - We will create a simple *forward-pass* NN model with tensorflow and keras
- Normal Data Evaluation
    - yay
- Complex Data Evaluation
    - yay
- Normal vs. Complex Evaluation
    - yay

<div style="
    padding: 15px 20px;
    margin: 10px 0;
    border-left: 8px solid #4F7942;
    background-color: rgba(255, 191, 0, 0.05);
    border-radius: 4px;
">

## Imports and Seed

- [Back to Table of Contents](#table-of-contents)

</div>

In [1]:
# Necessary for Modeling related functions
import modeling as m

import numpy as np
import pandas as pd
import networkx as nx
import igraph as ig
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split, GroupKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils import class_weight
import tensorflow as tf
from tensorflow.keras import layers, models
import joblib
import matplotlib.pyplot as plt
import matplotlib.lines as mlines

2026-03-10 17:37:08.095895: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
# Set the seed in multiple areas as the default 3703
m.set_reproducibility()

<div style="
    padding: 15px 20px;
    margin: 10px 0;
    border-left: 8px solid #4F7942;
    background-color: rgba(255, 191, 0, 0.05);
    border-radius: 4px;
">

## Machine Learning Model Selection and Definition

- [Back to Table of Contents](#table-of-contents)

</div>

### SUMMARY:
- We will use *Random Forest Classifier* to maintain as much explainability and generally solve the data imbalance in the complex data

---

### DISCUSSION:

Generally in the realm of Artificial Intelligence, Machine Learning (ML) models when compared with Neural Network (NN) models are primarily superior due to their explainability capabilities which is vital for deeper understanding of data and ultimately better decisionmaking.  Unfortunately, to keep things understandable for people, there's a lot of higher-level math and repetitive application of statistics observed in NNs - which is why they generally perform significantly better - that does not exist in ML models.  This is to say that the purpose of defining the best ML model for **BOTH** normal data and complex data training is primarily to observe if there's better performance with complex data training which in turn allows for more explainability of the dataset.

That being said, this dataset is a classification problem so classification models make the obvious sense to implement.  The initial assumption is that the *Decision Tree Classifier* (DTC) would be the ideal ML for comparison;  However, in `explore_complex_networks.ipynb`, we observed that the distribution of `benign` attacks became well over 99% of the data.  This data imbalance is something that DTCs fail at preventing bias and for this reason, a sort of randomness in which features to explore and how would effectively make the model blind to this data imbalance.  Thankfully, the *Random Forest Classifer* (RFC) is does exactly this.

Thus, for ML comparison of normal data and complex data, we will implement the RFC.

In [ ]:
def get_ml_model(trees:int=100) -> RandomForestClassifier:
    '''
    About
    -----
    - Creates and returns a basic sklearn RandomForestClassifier for model training

    Parameters
    ----------
    - trees (int) :
        - Default: 100
        - The number of decision trees to be created where each tree is randomly trained on a subset of the data.
          Essentially, this is like creating a voting block of whether or not something is significant during decisions

    Returns
    -------
    - RandomForestClassifier
    '''
    rfc_model = RandomForestClassifier(
        n_estimators=trees,      # This is just the number of "trees" we are creating
        class_weight='balanced', # This generally solves the imbalance issue
        max_features='sqrt',     # This generally solves the bias issue
        random_state=3703        # This is to ensure reproducibility
    )
    return rfc_model

<div style="
    padding: 15px 20px;
    margin: 10px 0;
    border-left: 8px solid #4F7942;
    background-color: rgba(255, 191, 0, 0.05);
    border-radius: 4px;
">

## Neural Network Model Selection and Definition

- [Back to Table of Contents](#table-of-contents)

</div>

### SUMMARY:

- We will create a simple *forward-pass* NN model with tensorflow and keras

---

### DISCUSSION:

Inversely from the `Machine Learning Model Selection and Definition` discussion, NNs when compared with ML models are primarily superior in performance due to heavy reliance of higher-level math and repetitive statistics.  The biggest emphasis is the notion of *backpropagation* where it is best to visualize as a decision tree;  From some initial input, we incrementally make decisions until we arrive at the destination and in this case, return a prediction of what the answer is.  However, unlike decisions tree where this is the end of the process, *backpropagation* will take a wrong answer as a sign to walk backwards in all their decisions and adjust *weights and biases* for every decision until the correct answer is arrived at.  This is conducted as many times as is defined in the NN model structure with other parameters which is generally why NNs are notorious for being a *black box* in the sense of being impossible to explain their decisions and interpret them as key points of the dataset.  To emphasize, because so much higher-level math and repetitive statistical weighting and biasing, NNs lose much of their explainability, but generally performs significantly better than ML models.  Basically, it brute forces a pattern in the dataset regardless if that pattern actually means something in order to get the most correct answers as possible.

With this said, this section is to delinate NNs "brute forcing" patterns from the normal dataset and NNs "brute forcing" patterns that are mathematically created with complex network ideology from the complex dataset.  In other words, will the NN perform better without being told what underlying pattern(s) may or may not exist via the normal dataset or will the NN perform better by being told what underlying pattern(s) may or may not exist via the complex dataset.

Thus, for NN comparison, we will utilize tensorflow and keras libraries to define an **as basic of a model as possible** to prevent extreme overfitting on whatever patterns the NN thinks it sees.  Additionally, to maintain as close of comparison to the ML model selection as a *Random Forest Classifier*, we will define layers to implement a **forward-pass** concept.

In [7]:
def get_nn_model(num_features_to_train:int,
                 num_targets:int=21) -> models.Sequential:
    '''
    About
    -----
    - Creates and returns a simple forward-pass Neural Network for model training
    - This definition is to closely resemble the RandomForestClassifer as much as possible via the forward-pass

    Parameters
    ----------
    - num_features_to_train (int) :
        - The number of features being used from the dataset to train the NN on
    - num_targets (int) :
        - The number of categorical targets to predict

    Returns
    -------
    - models.Sequential
        - A tensorflow.keras NN model
    '''
    # ----- Define NN Structure -------------------------------------------------------------------
    nn_model = models.Sequential([

        # Input layer (Starting point of decision making)
        layers.Input(shape=(num_features_to_train,)),

        # Small hidden layers to prevent "brute force" memorization
        layers.Dense(64, activation='relu'),
        layers.Dense(32, activation='relu'),

        # Output layer (using softmax for multiclass)
        layers.Dense(num_targets, activation='softmax') 
    ])
    
    # ----- Define Backpropagation Methodology ----------------------------------------------------
    nn_model.compile(
        optimizer='adam',                       # How weights/biases work
        loss='sparse_categorical_crossentropy', # How significant was the incorrectness
        metrics=['accuracy',                    # The metrics to optimize
                 tf.keras.metrics.SparseCategoricalAccuracy(name='cat_acc')
        ]
    )

    return nn_model

<div style="
    padding: 15px 20px;
    margin: 10px 0;
    border-left: 8px solid #4F7942;
    background-color: rgba(255, 191, 0, 0.05);
    border-radius: 4px;
">

## Normal Data Modeling

- [Back to Table of Contents](#table-of-contents)

</div>

### SUMMARY:

- 

---

a

In [3]:
# Read in the PREPARED normal dataset
normal_df = pd.read_parquet('datasets/prepared_normal_short.parquet')

In [4]:
# Prepare the data for ML/NN modeling
normal_data_preparation_dict = m.prepare_data_for_training(normal_df)

Warning: Rare classes detected [19]. Oversampling for stratification safety...

In [7]:
# Conduct ML model training/testing and saving of model/metrics
normal_ml_metrics = m.train_ml(normal_data_preparation_dict)

Training Random Forest on 2659367 rows...
Model successfully saved as models/ml_normal_model.joblib!
Testing Random Forest...
Random Forest testing complete!
Obtaining performance metrics and saving...
Random Forest metrics successfully saved as metrics/ml_normal_metrics.parquet!

In [8]:
normal_ml_metrics

                      target  precision    recall  f1-score        support
attack_name
analysis                   0   0.137931  0.727273  0.231884      11.000000
backdoor                   1   0.738739  0.872340  0.800000      94.000000
benign                     2   0.994977  0.597902  0.746947  124569.000000
bot                        3   1.000000  0.998590  0.999294     709.000000
brute_force                4   0.978583  0.967427  0.972973     614.000000
ddos                       5   0.993311  0.974160  0.983642  107624.000000
dos                        6   0.986448  0.955099  0.970521   88484.000000
exploits                   7   0.789809  0.794872  0.792332     156.000000
fuzzers                    8   0.688525  0.756757  0.721030     111.000000
generic                    9   0.913043  0.768293  0.834437      82.000000
infilteration             10   0.014198  0.579861  0.027717     576.000000
injection                 11   0.589749  0.845133  0.694714    3390.000000
mitm                      12   0.009166  0.815789  0.018129      38.000000
password                  13   0.882685  0.902785  0.892622    5709.000000
ransomware                14   0.833333  0.588235  0.689655      17.000000
reconnaissance            15   0.572576  0.935261  0.710299   13037.000000
scanning                  16   0.485452  0.936799  0.639508   18718.000000
shellcode                 17   0.181818  0.285714  0.222222       7.000000
theft                     18   0.027607  0.750000  0.053254      12.000000
worms                     19   0.000000  0.000000  0.000000       1.000000
xss                       20   0.918635  0.969964  0.943602   12152.000000
accuracy            accuracy   0.838627  0.838627  0.838627       0.838627
macro avg          macro avg   0.606504  0.762964  0.616418  376111.000000
weighted avg    weighted avg   0.942714  0.838627  0.868414  376111.000000

In [5]:
# Conduct NN model training/testing and saving of model/metrics
normal_nn_metrics = m.train_nn(normal_data_preparation_dict)

Training Neural Network on 2659367 rows...
Epoch 1/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.4803 - cat_acc: 0.4803 - loss: 2.2805 - val_accuracy: 0.5224 - val_cat_acc: 0.5224 - val_loss: 1.4627
Epoch 2/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.5303 - cat_acc: 0.5303 - loss: 1.5270 - val_accuracy: 0.5232 - val_cat_acc: 0.5232 - val_loss: 1.2983
Epoch 3/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.5483 - cat_acc: 0.5483 - loss: 1.2370 - val_accuracy: 0.5473 - val_cat_acc: 0.5473 - val_loss: 1.1607
Epoch 4/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.5734 - cat_acc: 0.5734 - loss: 1.1115 - val_accuracy: 0.5667 - val_cat_acc: 0.5667 - val_loss: 1.0590
Epoch 5/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.5989 - cat_acc: 0.5989 - loss: 0.9973 - val_accuracy: 0.6043 - val_cat_acc: 0.6043 - val_loss: 0.9840
Epoch 6/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6270 - cat_acc: 0.6270 - loss: 0.9508 - val_accuracy: 0.6086 - val_cat_acc: 0.6086 - val_loss: 0.9794
Epoch 7/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6342 - cat_acc: 0.6342 - loss: 0.9428 - val_accuracy: 0.6014 - val_cat_acc: 0.6014 - val_loss: 0.9811
Epoch 8/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6420 - cat_acc: 0.6420 - loss: 0.8651 - val_accuracy: 0.6605 - val_cat_acc: 0.6605 - val_loss: 0.8740
Epoch 9/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.6414 - cat_acc: 0.6414 - loss: 0.8306 - val_accuracy: 0.6587 - val_cat_acc: 0.6587 - val_loss: 0.8654
Epoch 10/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6503 - cat_acc: 0.6503 - loss: 0.8214 - val_accuracy: 0.6617 - val_cat_acc: 0.6617 - val_loss: 0.8393
Epoch 11/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6520 - cat_acc: 0.6520 - loss: 0.7778 - val_accuracy: 0.6665 - val_cat_acc: 0.6665 - val_loss: 0.8239
Epoch 12/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.6532 - cat_acc: 0.6532 - loss: 0.7942 - val_accuracy: 0.6763 - val_cat_acc: 0.6763 - val_loss: 0.8064
Epoch 13/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6573 - cat_acc: 0.6573 - loss: 0.7545 - val_accuracy: 0.6752 - val_cat_acc: 0.6752 - val_loss: 0.8208
Epoch 14/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6654 - cat_acc: 0.6654 - loss: 0.7363 - val_accuracy: 0.6772 - val_cat_acc: 0.6772 - val_loss: 0.7817
Epoch 15/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6670 - cat_acc: 0.6670 - loss: 0.7379 - val_accuracy: 0.6811 - val_cat_acc: 0.6811 - val_loss: 0.7739
Epoch 16/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.6719 - cat_acc: 0.6719 - loss: 0.7072 - val_accuracy: 0.6761 - val_cat_acc: 0.6761 - val_loss: 0.7516
Epoch 17/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6707 - cat_acc: 0.6707 - loss: 0.7016 - val_accuracy: 0.6752 - val_cat_acc: 0.6752 - val_loss: 0.7412
Epoch 18/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - accuracy: 0.6750 - cat_acc: 0.6750 - loss: 0.6907 - val_accuracy: 0.6811 - val_cat_acc: 0.6811 - val_loss: 0.7190
Epoch 19/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6778 - cat_acc: 0.6778 - loss: 0.6880 - val_accuracy: 0.6824 - val_cat_acc: 0.6824 - val_loss: 0.7040
Epoch 20/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6800 - cat_acc: 0.6800 - loss: 0.6654 - val_accuracy: 0.6829 - val_cat_acc: 0.6829 - val_loss: 0.7076
Epoch 21/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6858 - cat_acc: 0.6858 - loss: 0.6688 - val_accuracy: 0.6864 - val_cat_acc: 0.6864 - val_loss: 0.7021
Epoch 22/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6848 - cat_acc: 0.6848 - loss: 0.6673 - val_accuracy: 0.6907 - val_cat_acc: 0.6907 - val_loss: 0.6850
Epoch 23/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.6935 - cat_acc: 0.6935 - loss: 0.6473 - val_accuracy: 0.6983 - val_cat_acc: 0.6983 - val_loss: 0.6683
Epoch 24/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.6934 - cat_acc: 0.6934 - loss: 0.6445 - val_accuracy: 0.6930 - val_cat_acc: 0.6930 - val_loss: 0.6607
Epoch 25/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6938 - cat_acc: 0.6938 - loss: 0.6342 - val_accuracy: 0.6981 - val_cat_acc: 0.6981 - val_loss: 0.6618
Epoch 26/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.6994 - cat_acc: 0.6994 - loss: 0.6331 - val_accuracy: 0.7046 - val_cat_acc: 0.7046 - val_loss: 0.6605
Epoch 27/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7010 - cat_acc: 0.7010 - loss: 0.6194 - val_accuracy: 0.6993 - val_cat_acc: 0.6993 - val_loss: 0.6413
Epoch 28/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7040 - cat_acc: 0.7040 - loss: 0.6171 - val_accuracy: 0.7029 - val_cat_acc: 0.7029 - val_loss: 0.6368
Epoch 29/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7017 - cat_acc: 0.7017 - loss: 0.6282 - val_accuracy: 0.6918 - val_cat_acc: 0.6918 - val_loss: 0.6409
Epoch 30/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7067 - cat_acc: 0.7067 - loss: 0.6179 - val_accuracy: 0.7020 - val_cat_acc: 0.7020 - val_loss: 0.6255
Epoch 31/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7079 - cat_acc: 0.7079 - loss: 0.6010 - val_accuracy: 0.6970 - val_cat_acc: 0.6970 - val_loss: 0.6409
Epoch 32/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7101 - cat_acc: 0.7101 - loss: 0.5978 - val_accuracy: 0.7035 - val_cat_acc: 0.7035 - val_loss: 0.6137
Epoch 33/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7136 - cat_acc: 0.7136 - loss: 0.5953 - val_accuracy: 0.7068 - val_cat_acc: 0.7068 - val_loss: 0.6090
Epoch 34/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7143 - cat_acc: 0.7143 - loss: 0.5920 - val_accuracy: 0.6976 - val_cat_acc: 0.6976 - val_loss: 0.6158
Epoch 35/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7125 - cat_acc: 0.7125 - loss: 0.5922 - val_accuracy: 0.7141 - val_cat_acc: 0.7141 - val_loss: 0.6081
Epoch 36/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7157 - cat_acc: 0.7157 - loss: 0.5866 - val_accuracy: 0.7127 - val_cat_acc: 0.7127 - val_loss: 0.5941
Epoch 37/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7209 - cat_acc: 0.7209 - loss: 0.5935 - val_accuracy: 0.7197 - val_cat_acc: 0.7197 - val_loss: 0.5948
Epoch 38/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7165 - cat_acc: 0.7165 - loss: 0.5807 - val_accuracy: 0.7159 - val_cat_acc: 0.7159 - val_loss: 0.6010
Epoch 39/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7178 - cat_acc: 0.7178 - loss: 0.5715 - val_accuracy: 0.7192 - val_cat_acc: 0.7192 - val_loss: 0.5912
Epoch 40/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7231 - cat_acc: 0.7231 - loss: 0.5823 - val_accuracy: 0.7179 - val_cat_acc: 0.7179 - val_loss: 0.6138
Epoch 41/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - accuracy: 0.7198 - cat_acc: 0.7198 - loss: 0.5889 - val_accuracy: 0.7597 - val_cat_acc: 0.7597 - val_loss: 0.5930
Epoch 42/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7216 - cat_acc: 0.7216 - loss: 0.5724 - val_accuracy: 0.7226 - val_cat_acc: 0.7226 - val_loss: 0.5827
Epoch 43/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7232 - cat_acc: 0.7232 - loss: 0.5650 - val_accuracy: 0.7289 - val_cat_acc: 0.7289 - val_loss: 0.5798
Epoch 44/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7248 - cat_acc: 0.7248 - loss: 0.5735 - val_accuracy: 0.7196 - val_cat_acc: 0.7196 - val_loss: 0.5850
Epoch 45/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7275 - cat_acc: 0.7275 - loss: 0.5602 - val_accuracy: 0.7285 - val_cat_acc: 0.7285 - val_loss: 0.5765
Epoch 46/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7253 - cat_acc: 0.7253 - loss: 0.5681 - val_accuracy: 0.7495 - val_cat_acc: 0.7495 - val_loss: 0.5978
Epoch 47/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7290 - cat_acc: 0.7290 - loss: 0.5528 - val_accuracy: 0.7306 - val_cat_acc: 0.7306 - val_loss: 0.5753
Epoch 48/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7298 - cat_acc: 0.7298 - loss: 0.5847 - val_accuracy: 0.7295 - val_cat_acc: 0.7295 - val_loss: 0.5942
Epoch 49/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7305 - cat_acc: 0.7305 - loss: 0.5640 - val_accuracy: 0.7517 - val_cat_acc: 0.7517 - val_loss: 0.5855
Epoch 50/50
1299/1299 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.7291 - cat_acc: 0.7291 - loss: 0.5500 - val_accuracy: 0.7330 - val_cat_acc: 0.7330 - val_loss: 0.5695
Neural Network training completed!
Trained Neural Network for normal data successfully saved as models/nn_normal_model.keras!
Successfully saved off training histroy as metrics/nn_normal_history.parquet!
Testing Neural Network...
92/92 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Neural Network testing complete!
Obtaining performance metrics and saving...
Neural Network metrics successfully saved as metrics/nn_normal_metrics.parquet!

In [6]:
normal_nn_metrics

                      target  precision    recall  f1-score        support
attack_name
analysis                   0   0.101124  0.818182  0.180000      11.000000
backdoor                   1   0.863158  0.872340  0.867725      94.000000
benign                     2   0.986183  0.370710  0.538861  124569.000000
bot                        3   0.761290  0.998590  0.863941     709.000000
brute_force                4   0.868228  0.965798  0.914418     614.000000
ddos                       5   0.987204  0.922564  0.953790  107624.000000
dos                        6   0.981400  0.935615  0.957961   88484.000000
exploits                   7   0.033452  0.602564  0.063385     156.000000
fuzzers                    8   0.283582  0.684685  0.401055     111.000000
generic                    9   0.054187  0.670732  0.100273      82.000000
infilteration             10   0.009646  0.644097  0.019007     576.000000
injection                 11   0.243260  0.806490  0.373778    3390.000000
mitm                      12   0.004061  0.736842  0.008077      38.000000
password                  13   0.569671  0.778420  0.657883    5709.000000
ransomware                14   0.019006  0.764706  0.037090      17.000000
reconnaissance            15   0.523075  0.878960  0.655849   13037.000000
scanning                  16   0.475435  0.923336  0.627674   18718.000000
shellcode                 17   0.096774  0.857143  0.173913       7.000000
theft                     18   0.011011  0.916667  0.021761      12.000000
worms                     19   0.004348  1.000000  0.008658       1.000000
xss                       20   0.699949  0.796659  0.745180   12152.000000
accuracy            accuracy   0.733571  0.733571  0.733571       0.733571
macro avg          macro avg   0.408383  0.806909  0.436680  376111.000000
weighted avg    weighted avg   0.918445  0.733571  0.771717  376111.000000

<div style="
    padding: 15px 20px;
    margin: 10px 0;
    border-left: 8px solid #4F7942;
    background-color: rgba(255, 191, 0, 0.05);
    border-radius: 4px;
">

## Complex Data Modeling

- [Back to Table of Contents](#table-of-contents)

</div>

### SUMMARY:

- 

---

a

In [3]:
# Read in the PREPARED complex dataset
complex_df = pd.read_parquet('datasets/prepared_complex.parquet')

In [4]:
# Prepare the data for ML/NN modeling
complex_data_preparation_dict = m.prepare_data_for_training(complex_df, cols_to_drop=['attack', 'target', 'source_ip', 'destination_ip'])

Warning: Rare classes detected [19, 4, 18, 14]. Oversampling for stratification safety...

In [8]:
# Conduct ML model training/testing and saving of model/metrics
complex_ml_metrics = m.train_ml(complex_data_preparation_dict,
                                'models/ml_complex_model.joblib',
                                'metrics/ml_complex_metrics.parquet')

Training Random Forest on 168963 rows...
Model successfully saved as models/ml_complex_model.joblib!
Testing Random Forest...
Random Forest testing complete!
Obtaining performance metrics and saving...
Random Forest metrics successfully saved as metrics/ml_complex_metrics.parquet!

/opt/anaconda3/envs/COMP3703/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/COMP3703/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/COMP3703/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [9]:
complex_ml_metrics

                      target  precision    recall  f1-score       support
attack_name
analysis                   0   0.000000  0.000000  0.000000      2.000000
backdoor                   1   0.000000  0.000000  0.000000      2.000000
benign                     2   0.995878  0.999240  0.997556  23692.000000
bot                        3   0.000000  0.000000  0.000000      1.000000
brute_force                4   1.000000  1.000000  1.000000      1.000000
ddos                       5   0.428571  0.300000  0.352941     10.000000
dos                        6   0.700000  0.583333  0.636364     12.000000
exploits                   7   0.750000  0.750000  0.750000      4.000000
fuzzers                    8   0.000000  0.000000  0.000000      4.000000
generic                    9   0.333333  0.250000  0.285714      4.000000
infilteration             10   0.111111  0.016667  0.028986     60.000000
injection                 11   0.000000  0.000000  0.000000      6.000000
mitm                      12   0.000000  0.000000  0.000000      2.000000
password                  13   1.000000  0.142857  0.250000      7.000000
ransomware                14   1.000000  1.000000  1.000000      1.000000
reconnaissance            15   0.600000  0.428571  0.500000      7.000000
scanning                  16   0.888889  0.767123  0.823529     73.000000
shellcode                 17   0.285714  0.666667  0.400000      3.000000
theft                     18   1.000000  1.000000  1.000000      1.000000
worms                     19   1.000000  1.000000  1.000000      1.000000
xss                       20   0.500000  0.500000  0.500000      4.000000
accuracy            accuracy   0.994142  0.994142  0.994142      0.994142
macro avg          macro avg   0.504452  0.447831  0.453576  23897.000000
weighted avg    weighted avg   0.991797  0.994142  0.992749  23897.000000

In [5]:
# Conduct NN model training/testing and saving of model/metrics
complex_nn_metrics = m.train_nn(complex_data_preparation_dict,
                                'models/nn_complex_model.keras',
                                'metrics/nn_complex_history.parquet',
                                'metrics/nn_complex_metrics.parquet')

Training Neural Network on 168963 rows...
Epoch 1/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.3897 - cat_acc: 0.3897 - loss: 4.7292 - val_accuracy: 0.6525 - val_cat_acc: 0.6525 - val_loss: 2.7180
Epoch 2/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7470 - cat_acc: 0.7470 - loss: 2.9602 - val_accuracy: 0.8225 - val_cat_acc: 0.8225 - val_loss: 2.3263
Epoch 3/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8700 - cat_acc: 0.8700 - loss: 2.5865 - val_accuracy: 0.9121 - val_cat_acc: 0.9121 - val_loss: 1.7450
Epoch 4/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9216 - cat_acc: 0.9216 - loss: 2.3937 - val_accuracy: 0.9335 - val_cat_acc: 0.9335 - val_loss: 1.2857
Epoch 5/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8925 - cat_acc: 0.8925 - loss: 2.2264 - val_accuracy: 0.8557 - val_cat_acc: 0.8557 - val_loss: 1.0924
Epoch 6/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.7342 - cat_acc: 0.7342 - loss: 2.1033 - val_accuracy: 0.6731 - val_cat_acc: 0.6731 - val_loss: 1.0172
Epoch 7/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5774 - cat_acc: 0.5774 - loss: 2.0138 - val_accuracy: 0.5593 - val_cat_acc: 0.5593 - val_loss: 0.9628
Epoch 8/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5159 - cat_acc: 0.5159 - loss: 1.9456 - val_accuracy: 0.5028 - val_cat_acc: 0.5028 - val_loss: 0.9300
Epoch 9/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4829 - cat_acc: 0.4829 - loss: 1.8795 - val_accuracy: 0.4881 - val_cat_acc: 0.4881 - val_loss: 0.8943
Epoch 10/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4728 - cat_acc: 0.4728 - loss: 1.8304 - val_accuracy: 0.4743 - val_cat_acc: 0.4743 - val_loss: 0.8877
Epoch 11/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4679 - cat_acc: 0.4679 - loss: 1.7826 - val_accuracy: 0.4737 - val_cat_acc: 0.4737 - val_loss: 0.8671
Epoch 12/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4663 - cat_acc: 0.4663 - loss: 1.7509 - val_accuracy: 0.4707 - val_cat_acc: 0.4707 - val_loss: 0.8527
Epoch 13/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4642 - cat_acc: 0.4642 - loss: 1.7169 - val_accuracy: 0.4685 - val_cat_acc: 0.4685 - val_loss: 0.8427
Epoch 14/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4629 - cat_acc: 0.4629 - loss: 1.6845 - val_accuracy: 0.4666 - val_cat_acc: 0.4666 - val_loss: 0.8355
Epoch 15/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4616 - cat_acc: 0.4616 - loss: 1.6610 - val_accuracy: 0.4664 - val_cat_acc: 0.4664 - val_loss: 0.8281
Epoch 16/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4597 - cat_acc: 0.4597 - loss: 1.6395 - val_accuracy: 0.4647 - val_cat_acc: 0.4647 - val_loss: 0.8249
Epoch 17/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4599 - cat_acc: 0.4599 - loss: 1.6185 - val_accuracy: 0.4657 - val_cat_acc: 0.4657 - val_loss: 0.8203
Epoch 18/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4587 - cat_acc: 0.4587 - loss: 1.6002 - val_accuracy: 0.4650 - val_cat_acc: 0.4650 - val_loss: 0.8153
Epoch 19/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4583 - cat_acc: 0.4583 - loss: 1.5831 - val_accuracy: 0.4646 - val_cat_acc: 0.4646 - val_loss: 0.8117
Epoch 20/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4568 - cat_acc: 0.4568 - loss: 1.5680 - val_accuracy: 0.4627 - val_cat_acc: 0.4627 - val_loss: 0.8113
Epoch 21/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4556 - cat_acc: 0.4556 - loss: 1.5522 - val_accuracy: 0.4623 - val_cat_acc: 0.4623 - val_loss: 0.8109
Epoch 22/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4547 - cat_acc: 0.4547 - loss: 1.5397 - val_accuracy: 0.4611 - val_cat_acc: 0.4611 - val_loss: 0.8110
Epoch 23/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4544 - cat_acc: 0.4544 - loss: 1.5266 - val_accuracy: 0.4614 - val_cat_acc: 0.4614 - val_loss: 0.8099
Epoch 24/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4534 - cat_acc: 0.4534 - loss: 1.5158 - val_accuracy: 0.4611 - val_cat_acc: 0.4611 - val_loss: 0.8059
Epoch 25/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4538 - cat_acc: 0.4538 - loss: 1.5024 - val_accuracy: 0.4615 - val_cat_acc: 0.4615 - val_loss: 0.8015
Epoch 26/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4525 - cat_acc: 0.4525 - loss: 1.4926 - val_accuracy: 0.4608 - val_cat_acc: 0.4608 - val_loss: 0.8050
Epoch 27/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4528 - cat_acc: 0.4528 - loss: 1.4848 - val_accuracy: 0.4615 - val_cat_acc: 0.4615 - val_loss: 0.7974
Epoch 28/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4518 - cat_acc: 0.4518 - loss: 1.4741 - val_accuracy: 0.4606 - val_cat_acc: 0.4606 - val_loss: 0.7993
Epoch 29/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4517 - cat_acc: 0.4517 - loss: 1.4635 - val_accuracy: 0.4609 - val_cat_acc: 0.4609 - val_loss: 0.7973
Epoch 30/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4513 - cat_acc: 0.4513 - loss: 1.4547 - val_accuracy: 0.4608 - val_cat_acc: 0.4608 - val_loss: 0.7950
Epoch 31/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4514 - cat_acc: 0.4514 - loss: 1.4444 - val_accuracy: 0.4606 - val_cat_acc: 0.4606 - val_loss: 0.7961
Epoch 32/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4502 - cat_acc: 0.4502 - loss: 1.4394 - val_accuracy: 0.4599 - val_cat_acc: 0.4599 - val_loss: 0.7968
Epoch 33/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4507 - cat_acc: 0.4507 - loss: 1.4276 - val_accuracy: 0.4613 - val_cat_acc: 0.4613 - val_loss: 0.7912
Epoch 34/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4507 - cat_acc: 0.4507 - loss: 1.4206 - val_accuracy: 0.4600 - val_cat_acc: 0.4600 - val_loss: 0.7953
Epoch 35/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4513 - cat_acc: 0.4513 - loss: 1.4111 - val_accuracy: 0.4608 - val_cat_acc: 0.4608 - val_loss: 0.7923
Epoch 36/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4506 - cat_acc: 0.4506 - loss: 1.4038 - val_accuracy: 0.4609 - val_cat_acc: 0.4609 - val_loss: 0.7881
Epoch 37/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4509 - cat_acc: 0.4509 - loss: 1.3969 - val_accuracy: 0.4609 - val_cat_acc: 0.4609 - val_loss: 0.7909
Epoch 38/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4506 - cat_acc: 0.4506 - loss: 1.3897 - val_accuracy: 0.4611 - val_cat_acc: 0.4611 - val_loss: 0.7888
Epoch 39/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4489 - cat_acc: 0.4489 - loss: 1.3831 - val_accuracy: 0.4610 - val_cat_acc: 0.4610 - val_loss: 0.7861
Epoch 40/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4516 - cat_acc: 0.4516 - loss: 1.3760 - val_accuracy: 0.4610 - val_cat_acc: 0.4610 - val_loss: 0.7881
Epoch 41/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.4497 - cat_acc: 0.4497 - loss: 1.3705 - val_accuracy: 0.4611 - val_cat_acc: 0.4611 - val_loss: 0.7852
Epoch 42/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4510 - cat_acc: 0.4510 - loss: 1.3642 - val_accuracy: 0.4614 - val_cat_acc: 0.4614 - val_loss: 0.7835
Epoch 43/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4513 - cat_acc: 0.4513 - loss: 1.3585 - val_accuracy: 0.4615 - val_cat_acc: 0.4615 - val_loss: 0.7837
Epoch 44/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.4512 - cat_acc: 0.4512 - loss: 1.3530 - val_accuracy: 0.4614 - val_cat_acc: 0.4614 - val_loss: 0.7841
Epoch 45/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4525 - cat_acc: 0.4525 - loss: 1.3467 - val_accuracy: 0.4617 - val_cat_acc: 0.4617 - val_loss: 0.7825
Epoch 46/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4508 - cat_acc: 0.4508 - loss: 1.3420 - val_accuracy: 0.4619 - val_cat_acc: 0.4619 - val_loss: 0.7793
Epoch 47/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4523 - cat_acc: 0.4523 - loss: 1.3364 - val_accuracy: 0.4618 - val_cat_acc: 0.4618 - val_loss: 0.7794
Epoch 48/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.4527 - cat_acc: 0.4527 - loss: 1.3312 - val_accuracy: 0.4628 - val_cat_acc: 0.4628 - val_loss: 0.7790
Epoch 49/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4519 - cat_acc: 0.4519 - loss: 1.3261 - val_accuracy: 0.4631 - val_cat_acc: 0.4631 - val_loss: 0.7739
Epoch 50/50
83/83 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4526 - cat_acc: 0.4526 - loss: 1.3215 - val_accuracy: 0.4622 - val_cat_acc: 0.4622 - val_loss: 0.7766
Neural Network training completed!
Trained Neural Network for normal data successfully saved as models/nn_complex_model.keras!
Successfully saved off training histroy as metrics/nn_complex_history.parquet!
Testing Neural Network...
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
Neural Network testing complete!
Obtaining performance metrics and saving...
Neural Network metrics successfully saved as metrics/nn_complex_metrics.parquet!

/opt/anaconda3/envs/COMP3703/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/COMP3703/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/COMP3703/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [8]:
complex_nn_metrics

                      target  precision    recall  f1-score       support
attack_name
analysis                   0   0.000000  0.000000  0.000000      2.000000
backdoor                   1   0.000000  0.000000  0.000000      2.000000
benign                     2   0.999364  0.464545  0.634260  23692.000000
bot                        3   0.002959  1.000000  0.005900      1.000000
brute_force                4   0.000000  0.000000  0.000000      1.000000
ddos                       5   0.333333  0.200000  0.250000     10.000000
dos                        6   0.333333  0.166667  0.222222     12.000000
exploits                   7   1.000000  1.000000  1.000000      4.000000
fuzzers                    8   0.000000  0.000000  0.000000      4.000000
generic                    9   0.272727  0.750000  0.400000      4.000000
infilteration             10   0.004208  0.800000  0.008372     60.000000
injection                 11   0.000000  0.000000  0.000000      6.000000
mitm                      12   0.004831  0.500000  0.009569      2.000000
password                  13   0.010870  0.142857  0.020202      7.000000
ransomware                14   0.020833  1.000000  0.040816      1.000000
reconnaissance            15   0.200000  0.142857  0.166667      7.000000
scanning                  16   0.311321  0.904110  0.463158     73.000000
shellcode                 17   0.272727  1.000000  0.428571      3.000000
theft                     18   0.250000  1.000000  0.400000      1.000000
worms                     19   0.166667  1.000000  0.285714      1.000000
xss                       20   0.333333  0.500000  0.400000      4.000000
accuracy            accuracy   0.466293  0.466293  0.466293      0.466293
macro avg          macro avg   0.215072  0.503383  0.225498  23897.000000
weighted avg    weighted avg   0.992443  0.466293  0.630913  23897.000000

<div style="
    padding: 15px 20px;
    margin: 10px 0;
    border-left: 8px solid #4F7942;
    background-color: rgba(255, 191, 0, 0.05);
    border-radius: 4px;
">

## Normal vs. Complex Data

- [Back to Table of Contents](#table-of-contents)

</div>

### SUMMARY:

- 

---

a